import { Footer } from '@/components/footer'
import { Header } from '@/components/header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode
  params: { locale: string }
}

const langMap: Record<string, string> = {
  en: 'en-US',
  br: 'pt-BR',
  es: 'es-ES',
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  const selectedLang = langMap[locale]
  return (
    <html lang={selectedLang}>
      <body className={inter.className}>
        <div className="mx-auto flex min-h-screen flex-col">
          <Header />
          <div className="mt-20 flex-grow">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
